name: Android Create Jar

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Run emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: "37.0"
        target: google_apis_ps16k
        arch: x86_64
        profile: pixel_7_pro
        script: ./cli/hiddenjar doctor && ./cli/hiddenjar build

    - name: Upload jar
      uses: actions/upload-artifact@v7
      with:
        path: ./android-37-custom.jar
        archive: false
